[[AnnexD]]
[appendix,obligation=informative]
== MIM EXPRESS-G

The following diagrams provide a graphical representation of the MIM EXPRESS short listing defined in <<mim_express>>. The diagrams are presented in EXPRESS-G.

This annex contain two distinct representations of the Module Interpreted Model of this application module:

* a schema level representation which depicts the import of the constructs
defined in the MIM schema of other application modules or in a schema of Common
Resources documents,
in the MIM schema of this application module, through USE FROM statements;

* an entity level representation which presents the EXPRESS constructs defined
in the MIM schema of this application module and the references to imported
constructs that are specialized or referred to by the constructs of the MIM
schema of this application module.

[NOTE]
--
Both these representations are partial. The schema level representation does not present the MIM schema of modules that are indirectly imported. The entity level representation does not present the imported constructs that are not specialized or referred to by the constructs of the MIM schema of this application module.
--

The EXPRESS-G graphical notation is defined in ISO 10303-11.

[yaml2text,express-g-diagrams-mim.yaml,diagrams]
----
{% assign namespace = "mim" %}
include::diagrams.liquid[]
----

