
[[change_history]]
[appendix,obligation=informative]
== Change history

[[change_history_general]]
=== General

This annex documents the history of technical modifications made to
ISO/TS {docnumber}-{partnumber}.

[yaml2text,schemas.yaml,context]
------
{% liquid
assign path_prefix  = "../../schemas/modules/"
assign schema_name  = context.schemas.first[1].path | remove: path_prefix | split: "/" | first
assign changes_path = "changes.yaml"
assign mapping_path = schema_name | prepend: path_prefix | append: "/mapping.changes.yaml"
assign arm_path     = schema_name | prepend: path_prefix | append: "/arm.changes.yaml"
assign mim_path     = schema_name | prepend: path_prefix | append: "/mim.changes.yaml"

assign ordinal_numbers = "zero, " | append: "first, " | append: "second, " | append: "third, " | append: "fourth, " | append: "fifth, " | append: "sixth, " | append: "seventh, " | append: "eighth, " | append: "ninth, " | append: "tenth, " | append: "eleventh, " | append: "twelfth, " | append: "thirteenth, " | append: "fourteenth, " | append: "fifteenth, " | append: "sixteenth, " | append: "sixteenth, " | append: "seventeenth, " | append: "eighteenth, " | append: "nineteenth, " | append: "twentieth"

assign ordinal_numbers = ordinal_numbers | split: ", "
%}

{% capture arm_end_par %}
In addition, modifications have been made to the mapping specification, the MIM schema and the EXPRESS-G diagrams to reflect and be consistent with the modifications of the ARM.
{% endcapture %}

{% assign max_version = 2 %}

[yaml2text,{{changes_path}},data]
---
{% liquid
assign max_changes_ver = data.change_edition.last.version | plus: 0
if max_changes_ver > max_version
assign max_version = max_changes_ver
endif
%}
---

[yaml2text,{{mapping_path}},data]
---
{% liquid
assign max_mapping_ver = data.change_edition.last.version | plus: 0
if max_mapping_ver > max_version
assign max_version = max_mapping_ver
endif
%}
---

[yaml2text,{{arm_path}},data]
---
{% liquid
assign max_arm_ver = data.change_edition.last.version | plus: 0
if max_arm_ver > max_version
assign max_version = max_arm_ver
endif
%}
---

[yaml2text,{{mim_path}},data]
---
{% liquid
assign max_mim_ver = data.change_edition.last.version | plus: 0
if max_mim_ver > max_version
assign max_version = max_mim_ver
endif
%}
---

{% for ver in (2..max_version) %}

[[change_{{ver}}]]
=== Changes made in edition {{ver}}

[[summary_{{ver}}]]
==== Summary of changes

{% assign ver_before = ver | minus: 1 %}

The {{ ordinal_numbers[ver] }} edition of this document incorporated the modifications to the {{ ordinal_numbers[ver_before] }} edition listed below.

// changes from changes.yaml

{% if max_changes_ver %}
[yaml2text,{{changes_path}},data]
---
{% assign ver_str = ver | append: "" %}

// find version
{% for ed in data.change_edition %}
{% if ed.version == ver_str %}
{{ ed.description }}
{% endif %}
{% endfor %}
---
{% endif %}

// ARM schema changes

{% if max_arm_ver %}
[yaml2text,{{arm_path}},data]
----
{% assign ver_str = ver | append: "" %}

{% for ed in data.change_edition %}

// find version
{% if ed.version == ver_str %}

[[arm.changes{{ver}}]]
==== Changes made to the ARM

{% if ed.additions %}
The following ARM EXPRESS declarations and interface specifications have been added:

{% for change in ed.additions %}
* {{change.type}} {{change.name}}; {%- if change.interfaced_item %}(interface from {{change.interfaced_items}}){% endif %}
{%- if change.description %}
+
--
{{change.description}}
--
{% endif %}
{% endfor %}

{% endif %}

{% if ed.modifications %}
The following ARM EXPRESS declarations and interface specifications have been modified:

{% for change in ed.modifications %}
* {{change.type}} {{change.name}}; {%- if change.interfaced_item %}(interface from {{change.interfaced_items}}){% endif %}
{%- if change.description %}
+
--
{{change.description}}
--
{% endif %}
{% endfor %}
{% endif %}

{% if ed.deletions %}
The following ARM EXPRESS declarations and interface specifications have been deleted:

{% for change in ed.deletions %}
* {{change.type}} {{change.name}}; {%- if change.interfaced_item %}(interface from {{change.interfaced_items}}){% endif %}
{%- if change.description %}
+
--
{{change.description}}
--
{% endif %}

{% endfor %}
{% endif %}

{% endif %}

{% endfor %}

----

{{ arm_end_par }}

{% endif %}


// mapping changes

{% if max_mapping_ver %}
[yaml2text,{{mapping_path}},data]
----
{% assign ver_str = ver | append: "" %}

{% for ed in data.change_edition %}

// find version
{% if ed.version == ver_str %}

[[mapping.changes{{ver}}]]
==== Changes made to the mapping

The following changes have been made to the ARM to MIM mapping:

{% for change in ed.changes %}

* {{ change.change }}

{% endfor %}

{% endif %}
{% endfor %}
----
{% endif %}

// MIM schema changes

{% if max_mim_ver %}
[yaml2text,{{mim_path}},data]
----
{% assign ver_str = ver | append: "" %}

{% for ed in data.change_edition %}

// find version
{% if ed.version == ver_str %}

[[mim.changes{{ver}}]]
==== Changes made to the MIM

{% if ed.additions %}
The following MIM EXPRESS declarations and interface specifications have been added:

{% for change in ed.additions %}
* {{change.type}} {{change.name}}; {%- if change.interfaced_item %}(interface from {{change.interfaced_items}}){% endif %}
{%- if change.description %}
+
--
{{change.description}}
--
{% endif %}
{% endfor %}

{% endif %}

{% if ed.modifications %}
The following MIM EXPRESS declarations and interface specifications have been modified:

{% for change in ed.modifications %}
* {{change.type}} {{change.name}}; {%- if change.interfaced_item %}(interface from {{change.interfaced_items}}){% endif %}
{%- if change.description %}
+
--
{{change.description}}
--
{% endif %}
{% endfor %}
{% endif %}

{% if ed.deletions %}
The following MIM EXPRESS declarations and interface specifications have been deleted:

{% for change in ed.deletions %}
* {{change.type}} {{change.name}}; {%- if change.interfaced_item %}(interface from {{change.interfaced_items}}){% endif %}
{%- if change.description %}
+
--
{{change.description}}
--
{% endif %}

{% endfor %}
{% endif %}

{% endif %}

{% endfor %}
----
{% endif %}

{% endfor %}
------
