
[[change_history]]
[appendix,obligation=informative]
== Change history

[[general]]
=== General

This annex documents the history of technical modifications made to
ISO/TS {docnumber}-{partnumber}.

[yaml2text,changes.yaml,context]
------
{% liquid
assign schema       = context.schema
assign path_prefix  = "../../schemas/modules/"
assign mapping_path = schema | prepend: path_prefix | append: "/mapping.changes.yaml"
assign arm_path     = schema | prepend: path_prefix | append: "/arm.changes.yaml"
assign mim_path     = schema | prepend: path_prefix | append: "/mim.changes.yaml"
%}

{% assign max_version = context.change_edition.last.version | plus: 0 %}

[yaml2text,{{mapping_path}},data]
---
{% liquid
assign max_mapping_ver = data.change_edition.last.version | plus: 0
if max_mapping_ver > max_version
assign max_version = max_mapping_ver
endif
%}
---

[yaml2text,{{arm_path}},data]
---
{% liquid
assign max_arm_ver = data.change_edition.last.version | plus: 0
if max_arm_ver > max_version
assign max_version = max_arm_ver
endif
%}
---

[yaml2text,{{mim_path}},data]
---
{% liquid
assign max_mim_ver = data.change_edition.last.version | plus: 0
if max_mim_ver > max_version
assign max_version = max_mim_ver
endif
%}
---

{% for ver in (2..max_version) %}

[[change_{{ver}}]]
=== Changes made in edition {{ver}}

[[summary_{{ver}}]]
==== Summary of changes

The edition {{ ver }} of this part of ISO 10303 incorporated the modifications to the edition {{ ver | minus: 1 }} listed below.

{% assign ver_str = ver | append: "" %}

{% for ed in context.change_edition %}
// find version
{% if ed.version == ver_str %}
{{ed.description}}
{% endif %}
{% endfor %}


// mapping changes

{% if max_mapping_ver %}
[yaml2text,{{mapping_path}},data]
----
{% assign ver_str = ver | append: "" %}

{% for ed in data.change_edition %}

// find version
{% if ed.version == ver_str %}

[[mapping.changes{{ver}}]]
==== Changes made to the mapping

The following changes have been made to the ARM to MIM mapping:

{% for change in ed.changes %}

* {{ change.change }}

{% endfor %}

{% endif %}
{% endfor %}
----
{% endif %}


// ARM schema changes

{% if max_arm_ver %}
[yaml2text,{{arm_path}},data]
----
{% assign ver_str = ver | append: "" %}

{% for ed in data.change_edition %}

// find version
{% if ed.version == ver_str %}

[[arm.changes{{ver}}]]
==== Changes made to the ARM

{% if ed.additions %}
The following ARM EXPRESS declarations and interface specifications have been added:

{% for change in ed.additions %}
* {{change.type}} {{change.name}}; {%- if change.interfaced_item %}(interface from {{change.interfaced_items}}){% endif %}
{%- if change.description %}
+
--
{{change.description}}
--
{% endif %}
{% endfor %}

{% endif %}

{% if ed.modifications %}
The following ARM EXPRESS declarations and interface specifications have been modified:

{% for change in ed.modifications %}
* {{change.type}} {{change.name}}; {%- if change.interfaced_item %}(interface from {{change.interfaced_items}}){% endif %}
{%- if change.description %}
+
--
{{change.description}}
--
{% endif %}
{% endfor %}
{% endif %}

{% if ed.deletions %}
The following ARM EXPRESS declarations and interface specifications have been deleted:

{% for change in ed.modifications %}
* {{change.type}} {{change.name}}; {%- if change.interfaced_item %}(interface from {{change.interfaced_items}}){% endif %}
{%- if change.description %}
+
--
{{change.description}}
--
{% endif %}

{% endfor %}
{% endif %}

{% endif %}

{% endfor %}

----
{% endif %}


// MIM schema changes

{% if max_mim_ver %}
[yaml2text,{{mim_path}},data]
----
{% assign ver_str = ver | append: "" %}

{% for ed in data.change_edition %}

// find version
{% if ed.version == ver_str %}

[[mim.changes{{ver}}]]
==== Changes made to the MIM

{% if ed.additions %}
The following MIM EXPRESS declarations and interface specifications have been added:

{% for change in ed.additions %}
* {{change.type}} {{change.name}}; {%- if change.interfaced_item %}(interface from {{change.interfaced_items}}){% endif %}
{%- if change.description %}
+
--
{{change.description}}
--
{% endif %}
{% endfor %}

{% endif %}

{% if ed.modifications %}
The following MIM EXPRESS declarations and interface specifications have been modified:

{% for change in ed.modifications %}
* {{change.type}} {{change.name}}; {%- if change.interfaced_item %}(interface from {{change.interfaced_items}}){% endif %}
{%- if change.description %}
+
--
{{change.description}}
--
{% endif %}
{% endfor %}
{% endif %}

{% if ed.deletions %}
The following MIM EXPRESS declarations and interface specifications have been deleted:

{% for change in ed.modifications %}
* {{change.type}} {{change.name}}; {%- if change.interfaced_item %}(interface from {{change.interfaced_items}}){% endif %}
{%- if change.description %}
+
--
{{change.description}}
--
{% endif %}

{% endfor %}
{% endif %}

{% endif %}

{% endfor %}
----
{% endif %}

{% endfor %}
------
