[[annex_expg]]
[appendix,obligation=informative]
== EXPRESS-G diagrams

The diagrams in this annex correspond to the EXPRESS schemas
specified in this document. The diagrams use the EXPRESS-G
graphical notation for the EXPRESS language. EXPRESS-G is
defined in ISO 10303-11.


[lutaml_express, schemas, repo,config_yaml=schemas.yaml]
---
{% assign all_schemas = repo.schemas  %}

// ordered_schemas is a built-in variable that contains
// the selected schemas listed in schemas.yaml.
{% for schema in ordered_schemas %}

{% assign schema_id = schema.id %}
{% assign diagrams = schema.remark_items | where: "id", "__expressg" %}
{% assign diagrams = diagrams[0].remarks %}
{% assign number_of_diagrams = diagrams.size %}

// &#x200c; character represents an invisible element
// given that anchors cannot work without an element attached.
[[expg.{{ schema_id }}]]&#x200c;

{% for diagram in diagrams %}

{% capture caption -%}
EXPRESS-G diagram of {{ schema_id }} ({{ forloop.index }} of {{ number_of_diagrams }})
{% endcapture %}

.{{ caption }}
{{ diagram }}

{% endfor %}


{% endfor %}
---